### ISSUE TITLE
Wrong LICENSE? 

### ISSUE THREAD

**Issue by mpdf-tech** [LabyMod/ultralight-java#16]
I see that LabyMod is proprietary and I think that it uses this and https://github.com/LabyMod/opus-jni both licensed under GPL and not the LGPL license therefor using these is not allowed without LabyMod being also available under GPL as long as someone else has contributed code to these repositories which has not happened yet but could and it would lock the license.

My personal opinion is that LGPL/MIT better suites libraries like this anyways and it should be used as such and GPL should be used for standalone applications as intended.

**Comment by zortax** [comment]
You are wrong. LabyMedia GmbH holds the copyright the both libraries and LabyMod. Those libraries are being made available to the public under GPLv3, but as LabyMedia has the copyright, it can still use them I'm whatever proprietary context or modify them without releasing the source. 

Think of it as if LabyMedia issues a proprietary license to itself and a FOSS license to the public.

**Comment by zortax** [comment]
Oh, also LabyMod doesn't directly link against opus-jni. There is a addon (voice chat), that links against LabyMod and opus-jni.

Also, this addon doesn't use or modify any source code of opus-jni, it just distributes the binary as is, so GPL restrictions wouldn't apply anyway.

**Comment by mpdf-tech** [comment]
> You are wrong. LabyMedia GmbH holds the copyright the both libraries and LabyMod.

This is true as long as no one else contributes who does not work for your company.
https://www.gnu.org/licenses/gpl-faq.html#DeveloperViolate

> There is a addon (voice chat), that links against LabyMod and opus-jni.

Is this distributed with LabyMod or separately and is the source available? See https://www.gnu.org/licenses/gpl-faq.html#GPLInProprietarySystem https://www.gnu.org/licenses/gpl-faq.html#GPLPluginsInNF https://www.gnu.org/licenses/gpl-faq.html#NFUseGPLPlugins

Java JNI is not exempt from the restrictions of GPL and you are thinking about LGPL that allows you to use such code unmodified.

https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL
https://www.gnu.org/licenses/gpl-faq.html#WindowsRuntimeAndGPL

Are you guys not allowing people to contribute to these repos?

**Comment by Janrupf** [comment]
There are ongoing discussions whether linking with Java libraries is governed by GPL. However, we decided to change the license to LGPL (or something similar) soon, so that there will be no further issues. Thanks for notifying us :+1:

**Comment by zortax** [comment]
The Voice Chat is distributed separately, but as LabyMedia still holds the full copyright of this library (and libopusenc itself is BSD licensed), there is currently no issue whatsoever.

The JNI might not be exempt, but the voide chat is linking against a normal java library, so there are no code snippets directly compiled into it (header files etc.), just symbolic references. If this can be considered derivative work might be debatable, but as mentioned earlier it doesn't really matter as we hold the copyright anyway.

You are however right that license locking is technically a problem.
As we'd appreciate it if people would actually contribute to these (and future) repositories, we therefore decided to change the license of this repo (and opus-jni) to lesser GPL to make contributing easier (so contributorsdo not have to transfer copyright to us or anything alike).

**Comment by mpdf-tech** [comment]
Glad to see that you want people to contribute and I appreciate the response and may contribute to either project in the future if I ever use such projects.
