### ISSUE TITLE
How to set up custom rendering in divs

### ISSUE THREAD

**Issue by Martmists-GH** [LabyMod/ultralight-java#76]
The example somewhat shows compatibility with lwjgl, but how would I implement custom rendering for the contents of certain divs?

**Comment by zortax** [comment]
One way to implement this would be to pass the divs position and dimensions to the backend using JavaScript interop and then render stuff there.

**Comment by Martmists-GH** [comment]
For anyone with similar usecases, I used lwjgl's [yoga module](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/util/yoga/HolyGrail.java)
